<?php
// $Id: dependent_fields.module,v 1.1.2.20 2011/01/28 11:28:01 smoothify Exp $

/**
 * @file
 *   Adds AHAH Contoller / Dependent Fields functionality to CCK Fields.
 */

// Dependent Fields plugin hooks should always be available.
require_once dirname(__FILE__) . '/includes/plugins.inc';

// Temporarily here:
require_once dirname(__FILE__) . '/includes/form.inc';
require_once dirname(__FILE__) . '/includes/form_elements.inc';

/**
 * Implementation of hook_menu().
 *
 * Add a callback for the dependent fields ahah action
 */
function dependent_fields_menu() {
  $items['dependent_fields/callback/%/%/%'] = array(
    'page callback' => 'dependent_fields_callback',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/callback.inc',
  );
  // Overrid AHAH add more buttons callback.
  $items['dependent_fields/js_add_more'] = array(
    'page callback' => 'dependent_fields_add_more_js',
    'access arguments' => array('access content'),
    'file' => 'includes/callback.inc',
    'type' => MENU_CALLBACK,
  );

  $params = array();
  return array_merge(dependent_fields_invoke_all('menu', $params), $items);
}

/**
 * Implementation of hook_form_alter().
 *
 * Since we can't retrieve type and field information in hook_widget_settings,
 * we have to use form_alter instead.
 *
 */
function dependent_fields_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    // Add a handler for the content field edit form
    case 'content_field_edit_form':
      module_load_include('inc', 'dependent_fields', 'includes/admin');
      dependent_fields_content_edit_form($form);
      break;
  }

  // Alter the node form separately
  if (isset($form['type']['#value']) && $form_id == $form['type']['#value'] . '_node_form') {
    module_load_include('inc', 'dependent_fields', 'includes/form');
    dependent_fields_node_form_alter($form, $form_state, $form_id);
  }
}

/**
 * Implementation of hook_widget_settings_alter().
 */

function dependent_fields_widget_settings_alter(&$settings, $op, $widget) {
  module_load_include('inc', 'dependent_fields', 'includes/admin');
  _dependent_fields_widget_settings_alter($settings, $op, $widget);
}

/**
 * Implementation of hook_elements().
 */
function dependent_fields_elements() {
  $elements = array(
    'dependent_controller' => array(
      '#input' => TRUE,
      '#process' => array('dependent_fields_controller_process'),
    ),
    'dependent_wrapper' => array(
      '#input' => TRUE,
      '#process' => array('dependent_fields_wrapper_process'),
    ),
  );

  foreach (dependent_fields_allowed_widgets() as $widget) {
    $elements[$widget]['#process'] = array('dependent_fields_element_process');
    $elements[$widget]['#after_build'] = array('dependent_fields_element_after_build');
    $elements[$widget]['#element_validate'] = array('dependent_fields_element_validate');
  }

  $elements['text_textfield']['#process'][] = 'dependent_fields_textfield_process';
  $elements['optionwidgets_select']['#process'][] = 'dependent_fields_optionwidgets_process';
  $elements['optionwidgets_buttons']['#process'][] = 'dependent_fields_optionwidgets_process';

  return $elements;
}

/**
 * Implementation of hook_theme().
 */
function dependent_fields_theme() {
  $theme = array(
    'dependent_controller' => array(
      'arguments' => array('element' => NULL),
    ),
    'dependent_wrapper' => array(
      'arguments' => array('element' => NULL),
    ),
    'dependent_button' => array(
      'arguments' => array('element' => NULL),
    ),
  );
  $params = array();
  return array_merge(dependent_fields_invoke_all('theme', $params), $theme);
}

/**
 * Set the form_state for override functions where no form_state is passed in.
 */
function dependent_fields_set_form_state($form_state = array(), $clear = FALSE) {
  static $stored_state = array();

  if ($clear) {
    $stored_state = array();
    return TRUE;
  }

  if (!empty($form_state)) {
    $stored_state = $form_state;
  }

  return $stored_state;
}

/**
 * Implementation of hook_allowed_values().
 */
function dependent_fields_allowed_values($field) {
  $form_state = dependent_fields_set_form_state();
  $info = dependent_fields_build_field_info($field, $form_state);

  if (empty($info)) {
    return array();
  }
  $params = array($field, $info);
  $values = dependent_fields_invoke_field($field['type'], 'allowed_values', $params);


  $options = array();
  foreach ($values as $key => $value) {
    if (is_array($value) && (!empty($value['rendered']))) {
      $options[$key] = $value['rendered'];
    }
    else {
      $options[$key] = $value;
    }
  }

  // TODO , better logic to work when the none should show.
  if (!$field['required']) {
    $options = array('' => theme('optionwidgets_none', $field)) + $options;
  }

  return $options;
}

/**
 * Provide a list of potential controller fields in options format.
 */
function dependent_fields_potential_controller_options($field, $type, $include_none = TRUE) {
  $options = array();
  $field_types = _content_field_types();
  $potential_fields = dependent_fields_potential_controllers($field, $type);
  if (empty($potential_fields)) {
    return FALSE;
  }
  foreach ($potential_fields as $key => $value) {
    $field_type = $field_types[$value['type']];
    $text = t('@type: @field (@label)', array('@type' => t($field_type['label']), '@label' => t($value['name']), '@field' => $value['field_name']));
    $options[$key] = (drupal_strlen($text) > 80) ? truncate_utf8($text, 77) . '...' : $text;
  }
  // Sort the list by type, then by field name, then by label.
  asort($options);
  if ($include_none) {
    array_unshift($options, t('No Controller Field'));
  }
  return $options;
}

/**
 * Provide a list of potential controller fields.
 */
function dependent_fields_potential_controllers($field, $type) {
  $return = array();
  $info = dependent_fields_info();

  // Get all potential fields for the type
  foreach ($type['fields'] as $potential_field) {
    // Check if field type is allowed
    if (empty($info[$potential_field['type']])) {
      continue;
    }
    $field_info = $info[$potential_field['type']];
    $widget = $potential_field['widget'];
    $widget_type = isset($widget['widget_type']) ? $widget['widget_type'] : $widget['type'];
    // Exclude fields other than those with controllable widgets
    $allowed_widgets = $field_info['controller_widgets'];

    if (!is_array($allowed_widgets) || !in_array($widget_type, $allowed_widgets)) {
      continue;
    }
    // Exclude the current field
    if ($potential_field['field_name'] == $field['field_name']) {
      continue;
    }
    // Exlude fields already controlled by the current field
    if ($widget['dependent_fields']['controller_field'] == $field['field_name']) {
      continue;
    }

    $return[$potential_field['field_name']] = array(
      'name' => $potential_field['widget']['label'],
      'field_name' => $potential_field['field_name'],
      'type' => $potential_field['type'],
      'widget' => $potential_field['widget']['type'],
      '_weight' => $potential_field['widget']['weight'],
    );

  }
  return $return;
}


/**
 * Return the controller field.
 */
function dependent_fields_controller_field($field, $type) {
  if (is_array($type)) {
    $type_name = $type['type_name'];
  }
  else {
    $type_name = $type;
  }

  $return = FALSE;
  $widget = $field['widget'];
  $controller_field = $widget['dependent_fields']['controller_field'];
  if (!empty($controller_field)) {
    $return = content_fields($controller_field, $type_name);
  }

  return $return;
}

/**
 * Provide a themed list of controlled fields.
 */
function dependent_fields_controlled_fields_list($field, $type) {
  $items = array();
  $controlled_fields = dependent_fields_controlled_fields($field, $type);
  if (empty($controlled_fields)) {
    return FALSE;
  }
  // TODO: add a theming function to change output.
  foreach ($controlled_fields as $key => $value) {
    $items[$key] = array(
      'data' => '<strong>' . $value['widget']['label'] . '</strong> - ' . $value['field_name'] . ' - ' . $value ['type'],
    );
  }

  return $items;
}

/**
 * Provide a list of controlled fields.
 */
function dependent_fields_controlled_fields($field, $type) {
  $return = array();
  // Get list of allowed widgets for controlled fields
  $allowed_widgets = dependent_fields_allowed_widgets('', 'controlled');
  // Get all potential fields for the type
  foreach ($type['fields'] as $controlled_field) {
    $widget = $controlled_field['widget'];
    $widget_type = isset($widget['widget_type']) ? $widget['widget_type'] : $widget['type'];
    // Exclude fields other than those with controllable widgets
    if (!in_array($widget_type, $allowed_widgets)) {
      continue;
    }
    // Exclude the current field
    if ($controlled_field['field_name'] == $field['field_name']) {
      continue;
    }
    // Exlude fields not controlled by the current field
    if ($widget['dependent_fields']['controller_field'] != $field['field_name']) {
      continue;
    }

    $return[$controlled_field['field_name']] = $controlled_field;
  }

  return $return;
}

/**
 * Provide a list of controller fields enabled for a content type.
 */
function dependent_fields_type_controllers($type, $tree = NULL) {
  $controller_fields = array();
  $controlled_fields = array();
  // Get list of allowed widgets for both field types
  $allowed_widgets = dependent_fields_allowed_widgets();

  foreach ($type['fields'] as $field) {
    $widget = $field['widget'];
    $widget_type = isset($widget['widget_type']) ? $widget['widget_type'] : $widget['type'];
    // Exclude fields other than those with allowed widgets
    if (!in_array($widget_type, $allowed_widgets)) {
      continue;
    }
    if (!empty($field['widget']['dependent_fields']['controller_field'])) {
      $controlled_fields[$field['widget']['dependent_fields']['controller_field']][$field['field_name']] = array();
    }
    else {
      $controller_fields[$field['field_name']] = array();
    }
  }

  // Build hierarchical tree of controller fields
  dependent_fields_type_controllers_tree($controller_fields, $controlled_fields);

  // Clear out fields with no dependent fields.
  foreach ($controller_fields as $key => $field) {
    if (empty($field)) {
      unset($controller_fields[$key]);
    }
  }

  return $controller_fields;
}

/**
 * Recursive function to fill out a tree of controller and controlled fields.
 */
function dependent_fields_type_controllers_tree(&$tree, $controlled_fields) {
  foreach ($tree as $field_name => $field_array) {
    if (!empty($controlled_fields[$field_name]) && is_array($controlled_fields[$field_name])) {
      $tree[$field_name] = $controlled_fields[$field_name];
      dependent_fields_type_controllers_tree($tree[$field_name], $controlled_fields);
    }
  }
}

/**
 * Return the values inside form_state for a given field.
 */

function dependent_fields_retrieve_field_value($field, $form_state) {
  $return = FALSE;
  $form_value = !empty($form_state['values'][$field['field_name']]) ? $form_state['values'][$field['field_name']] : null;
  $params = array($field, $form_value, $form_state);
  $return = dependent_fields_invoke_field($field['type'], 'retrieve_field_value', $params);
  return $return;
}

/**
 * Return the values inside form_state for a given field.
 */

function dependent_fields_retrieve_field_keys($field, $values) {
  $return = FALSE;
  $params = array($field, $values);
  $return = dependent_fields_invoke_field($field['type'], 'retrieve_field_keys', $params);
  return $return;
}

/**
 * Return the titles inside form_state for a given field.
 */

function dependent_fields_retrieve_field_titles($field, $values) {
  $return = FALSE;
  $params = array($field, $values);
  $return = dependent_fields_invoke_field($field['type'], 'retrieve_field_titles', $params);
  return $return;
}

/**
 * Function to override fields on the fly, so we can use our own validation and
 * allowed option.
 */
function dependent_fields_set_field_overrides(&$fields, $tree = NULL, $reset = FALSE) {
  static $overrides = array();
  // Check for reset param, and if there revert fields back to their original modules
  if ($reset && !empty($overrides)) {
    foreach ($overrides as $field => $original) {
      $fields[$field]['module'] = $original;
    }
    unset($overrides);
    return;
  }

  if (empty($tree)) {
    return $overrides;
  }
  $another_level = FALSE;
  foreach ($tree as $controller_name => $field_array) {
    if (empty($field_array)) {
      continue;
    }
    foreach ($field_array as $field_name => $controlled_field) {
      // Check to see if this field has already been set.
      if (empty($overrides[$field_name])) {
        if ($fields[$field_name]['module'] != 'dependent_fields') {
          $overrides[$field_name] = $fields[$field_name]['module'];
          $fields[$field_name]['module'] = 'dependent_fields';
        }
      }
      // Process any controlled fields
      if (!empty($controlled_field)) {
        $another_level = TRUE;
      }
    }
    if ($another_level) {
      dependent_fields_set_field_overrides($fields, $field_array);
    }
  }

}


/**
 * Submit handler for fallback submit button.
 */

function dependent_fields_fallback_submit($form, &$form_state) {
  unset($form_state['submit_handlers']);
  $form_state['rebuild'] = TRUE;
}


/**
 * Add the ahah controller settings
 */
function dependent_fields_set_ahah_settings(&$element, $field) {
  $delta = isset($element['#delta']) ? $element['#delta'] : 0;
  $element['#ahah'] = array(
    'path' => 'dependent_fields/callback/'.   $field['type_name'] .'/'. $field['field_name'] .'/'. $delta,
    'wrapper' => $field['field_name'] .'-ahah-wrapper',
    'method' => 'replace',
    'effect' => 'fade',
    //'event' => 'keypress',
  );
}

/**
 * Get the ahah_wrapper element
 */
function dependent_fields_get_ahah_wrapper_element($form, $field, $type, $level = 0) {
  $field_name = $field['field_name'];
  $controller_field = dependent_fields_controller_field($field, $type);
  $controlled_fields = dependent_fields_controlled_fields($field, $type);

  if (!empty($controller_field)) {
    $form = dependent_fields_get_ahah_wrapper_element($form, $controller_field, $type, $level + 1);
  }

  $field_element = &dependent_fields_retrieve_field_element($form, $type, $field_name);

  if (!empty($field_element['#controlled_field'])) {
    $parent = &dependent_fields_retrieve_field_parent_element($form, $type, $field_element['#controlled_field']);
    $form_element = $parent[$field_name . '_ahah_wrapper'];
  }
  elseif (!empty($field_element['#controlled_group'])) {
    $parent = $form[$field_element['#controlled_group']];
    $form_element = $parent[$field_name . '_ahah_wrapper'];
  }
  elseif (is_array($field_element['#fields'])) {
    $form_element = $field_element[$field_name . '_ahah_wrapper'];
  }

  return $form_element;
}
/**
 * Return a list of valid field elements to apply ahah settings to.
 */
function dependent_fields_get_ahah_elements($field = NULL) {
  $valid = array(
    'submit', 'button', 'image_button', 'password', 'textfield', 'textarea',
    'blur', 'radio', 'checkbox', 'select'
  );
  if (!empty($field)) {
    $params = array();
    $valid = array_merge($valid, dependent_fields_invoke_field($field['type'], 'get_ahah_elements', $params));
  }
  return $valid;
}


/**
 * Locate the actual field element, and apply the controller ahah settings
 *
 * TODO: split the controller and controlled fields into their own functions with invokes.
 */
function dependent_fields_set_field_elements(&$form, &$field, $type = 'controller') {
  $field_columns = array_keys($field['columns']);
  $field_column = $field_columns[0];
  // Get a list of elements that we can apply ahah settings on.
  $valid_field_elements = dependent_fields_get_ahah_elements($field);

  foreach (element_children($form) as $key) {
    dependent_fields_set_field_elements($form[$key], $field, $type);
  }
  // Check to see if we have a valid form element here
  if (in_array($form['#type'], $valid_field_elements)) {
    if ($type == 'controller') {
      dependent_fields_set_ahah_settings($form, $field);
      $form = form_expand_ahah($form);
    }
    elseif ($type == 'controlled') {

    }

  }
}


function dependent_fields_allowed_values_mapping($field) {
  static $controller_mappings = array();

  $cid = $field['field_name'];

  if (isset($controller_mappings[$cid])) {
    return $controller_mappings[$cid];
  }

  $mapping = $field['widget']['dependent_fields']['allowed_mapping']['mapping'];
  $controller_mappings[$cid] = array();

  $list = explode("\n", $mapping);
  $list = array_map('trim', $list);
  $list = array_filter($list, 'strlen');
  foreach ($list as $opt) {
    // Sanitize the user input with a permissive filter.
    $opt = content_filter_xss($opt);
    if (strpos($opt, '|') !== FALSE) {
      list($key, $value_list) = explode('|', $opt);
      $values = explode(',', $value_list);
      $controller_mappings[$cid][$key] = $values;
    }
    else {
      continue;
    }
  }
  return $controller_mappings[$cid];
}

function dependent_fields_filter_allowed_values($all_values, $mapping, $keys) {
  $allowed_values = array();
  if (!is_array($keys)) {
    return $allowed_values;
  }
  foreach ($keys as $key) {
    if (!is_array($mapping[$key])) {
      continue;
    }
    foreach ($mapping[$key] as $value) {
      if (!empty($all_values[$value])) {
        $allowed_values[$value] = $all_values[$value];
      }
    }
  }
  return $allowed_values;
}

/**
 * Process the dependent_controller element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function dependent_fields_controller_process($element, $edit, &$form_state, $form) {
  dependent_fields_set_form_state($form_state);
  if (!empty($element['#controller_field_name'])) {
    $attributes = array('class' => 'dependent-fields-controller clear-block');
    $element['#prefix'] = '<div '. drupal_attributes($attributes) .'>';
    $element['#suffix'] = '</div>';
    $element['#weight'] = $element[$element['#controller_field_name']]['#weight'];
    $element[$element['#controller_field_name']]['#weight'] = 0;

    $element['fallback_button'] = array(
      '#type' => 'submit',
      '#button_type' => 'submit',
      '#value' => t('Continue'),
      '#attributes' => array('class' => 'ahah-fallback-button'),
      '#submit' => array('dependent_fields_fallback_submit'),
      '#prefix' => '<div class="fallback-button-wrapper">',
      '#suffix' => '</div>',
      '#weight' => 1,
    );

    if (!empty($element['#fields']) && is_array($element['#fields'])) {
      $wrapper = array();
      $wrapper['#type'] = 'dependent_wrapper';
      $wrapper['#parent_field'] = $element['#controller_field_name'];
      $wrapper['#weight'] = 2;
      $wrapper['#field_count'] = $element['#field_count'];
      $wrapper['#fields'] = $element['#fields'];
      $element[$element['#controller_field_name'] . '_ahah_wrapper'] = $wrapper;
    }

  }
  return $element;
}

/**
 * Process the dependent_wrapper element.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $form['#field_info'][$element['#field_name']].
 */
function dependent_fields_wrapper_process($element, $edit, &$form_state, $form) {
  if (!empty($element['#parent_field'])) {
    $wrapper_id = $element['#parent_field'] . '-ahah-wrapper';
    $attributes = array('id' => $wrapper_id, 'class' => 'dependent-fields-wrapper');
    $element['#prefix'] = '<div '. drupal_attributes($attributes) .'>';
    $element['#suffix'] = '</div>';
  }

  if (is_array($element['#fields'])) {
    foreach ($element['#fields'] as $field_name => $field_element) {
      // Need to add this cause for some reason the element is in
      // the 0 element instead of the root. eg text_textfield.
      if(is_array($field_element[0])) {
        foreach($field_element[0] as $key => $value) {
          $field_element[$key] = isset($field_element[$key])? $field_element[$key]: $value;
        }
        unset($field_element[0]);
      }
      // If there is only one field, we set the weight of the wrapper to match it.
      if ($element['#field_count'] == 1) {
        $element['#weight'] = $field_element['#weight'];
      }
      // Set the preprocess function. At this stage the process key is not set, however once we set it here,
      // this prevents it from being set in the normal fashion. So, we need to retrieve the element info and
      // do it ourselves.
      $element_info = _element_info($field_element['#type']);
      // Set our preprocess function.
      $field_element['#process'] = array('dependent_fields_element_preprocess');
      // Merge in other functions for this element.
      $field_element['#process'] = array_merge($field_element['#process'], $element_info['#process']);
      // Todo - should we add dependent_fields_element_preprocess here instead of in the hook_elements?
      
      $element[$field_name] = $field_element;
    }
  }
  
  return $element;
}

/**
 * FAPI theme for an individual elements.
 */
function theme_dependent_controller($element) {
  return $element['#children'];
}

/**
 * FAPI theme for an individual elements.
 */
function theme_dependent_wrapper($element) {
  return $element['#children'];
}

/**
 * Disable validation for all of the form.
 */
function dependent_fields_replace_string_tokens($info, $string, $delimiter = '+') {
  $return = $string;

  $values = $info['controller_value'];
  $keys = dependent_fields_retrieve_field_keys($info['controller_field'], $values);
  $titles = dependent_fields_retrieve_field_titles($info['controller_field'], $values);

  $search = array(
    '[controller_key]',
    '[controller_key_multiple]',
    '[controller_title]',
    '[controller_title_multiple]',
  );

  $replace = array(
    $keys[0],
    implode($delimiter, $keys),
    $titles[0],
    implode($delimiter, $titles),
  );

  $return = str_replace($search, $replace, $string);

  return $return;
}


/**
 * Builds a formatted list of our simple tokens
 */
function dependent_fields_string_tokens_help($delimiter = '+', $prefix = '[', $suffix = ']') {
  $tokens = array(
    'controller_key' => t('The controller field\'s key value. If the field has multiple values then the first is used.'),
    'controller_key_multiple' => t('All the controller field\'s key values, separated by %delimiter.', array('%delimiter' => $delimiter)),
    'controller_title' => t('The controller field\'s title. If the field has multiple values then the first is used.'),
    'controller_title_multiple' => t('All the controller field\'s titles, separated by %delimiter', array('%delimiter' => $delimiter)),
  );

  $headers = array(t('Token'), t('Replacement value'));
  $rows = array();
  foreach ($tokens as $token => $description) {
    $row = array();
    $row[] = $prefix . $token . $suffix;
    $row[] = $description;
    $rows[] = $row;
  }

  $output = theme('table', $headers, $rows, array('class' => 'description'));
  return $output;
}

/**
 * Function to add dependent fields CSS to the form.
 */
function dependent_fields_add() {
  static $added = FALSE;
  if (!$added) {
    drupal_add_css(drupal_get_path('module', 'dependent_fields') . '/dependent_fields.css');
    $added = TRUE;
  }
}